<?php
/**
 * Created by PhpStorm.
 * User: achref
 * Date: 01/04/2018
 * Time: 16:23
 */

namespace AppBundle\Repository;

/**
 * LigneachatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneachatRepository extends \Doctrine\ORM\EntityRepository
{
    public function  removeAll($id_achat)
    {
        $qd = $this->createQueryBuilder('n');
        $qd->delete()
            ->where('n.idAchat = :id')
            ->setParameter('id',$id_achat);
        $query = $qd->getQuery();
        $result = $query->getResult();
    }
}