<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllDispo($keyword)
    {
        $querybuilder = $this->createQueryBuilder("p");
        return $querybuilder
            ->where("p.quantite >0")
            ->andWhere("p.type like ?1")
            ->setParameter(1, $keyword)
            ->getQuery()
            ->getResult();
    }

    public function Order($type,$critere)
    {
        if($critere=="ASC")
        {
            $querybuilder = $this->createQueryBuilder("p");
            return $querybuilder
                ->where("p.type like ?1")
                ->orderBy("p.prix",'ASC')
                ->setParameter(1, $type)
                ->getQuery()
                ->getResult();
        }
        $querybuilder = $this->createQueryBuilder("p");
        return $querybuilder
            ->where("p.type like ?1")
            ->orderBy("p.prix",'DESC')
            ->setParameter(1, $type)
            ->getQuery()
            ->getResult();

    }

    public function searchByKeyword($key)
    {
        return $this->createQueryBuilder('p')
            ->where("p.libelle like ?1")
            ->orWhere("p.type like ?2")
            ->setParameter(1, $key.'%')
            ->setParameter(2, $key.'%')
            ->getQuery()
            ->getResult();
    }


}
