<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function articlesParPrix()
    {
        $querybuilder = $this->createQueryBuilder("article");
        return $querybuilder->addOrderBy("article.prix")->getQuery()->getResult();
    }


    public function searchByKeyword($keyword)
    {
        $querybuilder = $this->createQueryBuilder("p");
        return $querybuilder
            ->where($querybuilder
                ->expr()
                ->like("p.libelle", ":keyword")
            )
            ->setParameter("keyword","%".$keyword."%")
            ->getQuery()
            ->getResult();
    }

    public function getArticles($first_result, $max_results = 6)
    {
        $qb = $this->createQueryBuilder('article');
        $qb
            ->select('produit')
            ->setFirstResult($first_result)
            ->setMaxResults($max_results);

        $pag = new Paginator($qb);
        return $pag;
    }

    public function  getLatestArticles(){
        $qb = $this->createQueryBuilder('article');
        $qb
            ->select('article')
            ->where("article.vendu= :rep ")
            ->setParameter(":rep", false)
            ->setMaxResults(6);
        return $qb->getQuery()->getResult();
    }

}
